services:
  aqsolpred-web:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${AQSOLPRED_HOST_PORT:-8501}:8501"
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
