[workspace]
authors = ["Murat Cihan Sorkun"]
channels = ["conda-forge", "rdkit"]
name = "aqsolpred-env"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.8.*"
rdkit = "2019.9.3.*"
numpy = "1.18.1.*"
setuptools = "<82.0.0"
protobuf = "<4"
click = "<8.1.0"
boost-cpp = "1.70.0.*"
boost = "1.70.0.*"

[pypi-dependencies]
streamlit = "==0.69.2"
numpy = "==1.18.1"
scikit-learn = "==0.22.2.post1"
mordred = "==1.2.0"
xgboost = "==1.0.2"
